### ISSUE TITLE
Meson Postinstall with DESTDIR?

### ISSUE THREAD

**Issue by louis77** [Henryws/pacstall-programs#10]
**Describe the bug**
Usually meson_postinstall scripts end with this:

```
if not environ.get('DESTDIR'):
    print('Compiling gsettings schemas…')
    subprocess.call(['glib-compile-schemas', schemadir])
    print('Updating desktop database…')
    subprocess.call(['update-desktop-database', '-q', desktop_database_dir])
    print('Updating icon cache…')
    subprocess.call(['gtk-update-icon-cache', '-qtf', path.join(datadir, 'icons', 'hicolor')])
```
Package managers usually do these calls which is why they are only executed when DESTDIR is not defined.
`pacstall` doesn't do these calls so my app is crashing on start because the schema is not compiled and also the desktop icon is missing.

**Expected behavior**
Either `pacstall` should do these three calls _or_ provide an environment variable so in the script it can be checked for that or we have to duplicate the calls into the pacscript.

**Additional context**
It seems AUR is executing these calls after install.

**Comment by Henryws** [comment]
What package are you installing?

**Comment by louis77** [comment]
I'm currently preparing a package, so it's local. I can push it and we can look from there.

**Comment by Henryws** [comment]
Could you post the contents here first before doing a PR

**Comment by Henryws** [comment]
I’m not that good with meson so could you explain the problem like I’m 5. Sorry about my unknowingness

**Comment by louis77** [comment]
```
name="tuner"
version="1.3.1"
license="GPL-3.0"
url="https://github.com/louis77/tuner/archive/refs/tags/1.3.1.zip"
build_depends="meson valac libgtk-3-dev libgranite-dev libsoup2.4-dev libgstreamer1.0-dev libgstreamer-p>
depends=""
description="Discover and listen to internet radio stations."
hash="4b8cc5941652ebb872793bbc0f3d56e1c5d4423e6cf8d16aaeea25999075c1aa"

prepare() {
    meson builddir --prefix=/usr 
}

build() {
    ninja -C builddir -j$(nproc) 
}

install() {
    sudo DESTDIR=/usr/src/pacstall/tuner ninja -C builddir install
}
```

Build and install worked, but those calls above should be done by the package manager.

**Comment by Henryws** [comment]
What do you mean done by the package manager? Because I have gnome-tweak and it works fine. It’s almost just like this:

```bash
name="gnome-tweaks"
pkgname="gnome-tweaks"
url="https://github.com/GNOME/gnome-tweaks/archive/refs/tags/40.0.zip"
version="40.0"
license="GPL-3.0"
build_depends="meson"
depends="gsettings-desktop-schemas python3 gnome-settings-daemon gnome-shell-common mutter-common python3-gi gir1.2-gtk-3.0 gir1.2-gnomedesktop-3.0 gir1.2-handy-0.0 gir1.2-soup-2.4 gir1.2-notify-0.7 gir1.2-glib-2.0 gir1.2-pango-1.0 gnome-shell-extension-prefs"
gives="gnome-tweaks"
breaks=""
description="Graphical interface for advanced GNOME 3 settings"

prepare() {
          meson builddir
}

build() {
        ninja -C builddir
}

install() {
          sudo DESTDIR=/usr/src/pacstall/gnome-tweaks ninja -C builddir install -j$(nproc)
}
```

**Comment by louis77** [comment]
Everything works fine (build and install) but usually the three calls I mentioned above are executed by the package manager _after_ install. Which is why usually in meson post_install scripts there is the  `if not get.environ("DESTDIR") ` directive for that.
But since `pacstall` requires the use of `DESTDIR` the post install script will do nothing.

**Comment by Henryws** [comment]
Would it be possible to remove the if not get stuff or is that important?

**Comment by Henryws** [comment]
Would it be possible to do a `mkdir /usr/src/pacstall/tuner` and `meson builddir --prefix=/usr/src/pacstall/tuner`

**Comment by louis77** [comment]
Hmm.... let me try that :)

**Comment by louis77** [comment]
But on the other hand, those calls should also be made by `pacstall` when an application ins removed. 
Otherwise the desktop icon will stay but won't work anymore.

**Comment by Henryws** [comment]
That would require some special stuff that I could work on later. I’m in school so can’t do it now. Did it install?

**Comment by louis77** [comment]
Just for reference, these are the calls:

```
glib-compile-schemas /usr/share/glib-2.0/schemas
update-desktop-database -q /usr/share/applications
gtk-update-icon-cache -qtf  /usr/share/icons/hicolor (optional)
```

**Comment by louis77** [comment]
Now I get 

```
[+] INFO: Symlinking files
WARNING! stowing tuner would cause conflicts:
  * existing target is not owned by stow: bin
All operations aborted.
[!] ERROR: Package contains links to files that exist on the system
```
I have to find and clean which files are now in the way.

**Comment by Henryws** [comment]
So those are just commands that are run after removal?

**Comment by louis77** [comment]
After install and after removal.

**Comment by Henryws** [comment]
About the bin thing. Try running `sudo pacstall -R tuner`

**Comment by Henryws** [comment]
I could try to add pre and post install capabilities

**Comment by Henryws** [comment]
I made a new branch with the new function for post installation scripts. Add the function `postinst` to your pacscript with the commands:
```bash
glib-compile-schemas /usr/share/glib-2.0/schemas
update-desktop-database -q /usr/share/applications
```
to it. Remember to use the new branch or edit `/usr/share/pacstall/scripts/install-local.sh` to add this to the end:
```bash
type -t postinst > /dev/null 2>&1
if [[ $? -eq 0 ]] ; then
   postinst
fi
```

**Comment by louis77** [comment]
> Would it be possible to do a mkdir -p /usr/src/pacstall/tuner and meson builddir --prefix=/usr/src/pacstall/tuner So you don’t use the DESTDIR

Just for the record, I tried this but then this happens:

```
[+] INFO: Symlinking files
WARNING! stowing tuner would cause conflicts:
  * existing target is neither a link nor a directory: usr/share/applications/mimeinfo.cache
  * existing target is neither a link nor a directory: usr/share/glib-2.0/schemas/gschemas.compiled
  * existing target is neither a link nor a directory: usr/share/icons/hicolor/icon-theme.cache
All operations aborted.
[!] ERROR: Package contains links to files that exist on the system

```

I'll try the new branch now.

**Comment by louis77** [comment]
Ok, postinst() method worked!
I also tested uninstall and re-install. 
When you can make the remove() function possible that would be great!

**Comment by Henryws** [comment]
I can do it now. Give me a couple minutes. I’ll have to update the `make-a-pacscript` file but yeah. It works!

**Comment by Henryws** [comment]
I added some stuff to the branch. In your pacscript, if you add `removescript=yes` to your script and you add the function `removescript` with your code, it should work. Remember to get the changes from the branch correctly

**Comment by Henryws** [comment]
I can make it better but I hacked it together. It requires and internet connection to source the pacscript which has the `removescript` function
