### ISSUE TITLE
Feature Request: i3-gaps

### ISSUE THREAD

**Issue by 1ctinus** [Henryws/pacstall-programs#12]
For some reason, Debian and ubuntu do not have i3-gaps in it's repositories, and was super frustrating to build. There is already a script to install i3-gaps for debian (https://raw.githubusercontent.com/maestrogerardo/i3-gaps-deb/master/i3-gaps-deb), so i think it should be able to be ported.

**Comment by Henryws** [comment]
I don’t make packages for people on request. You can ask someone on the discord for help if you want. If they can’t I can help you but you will maintain it

**Comment by 1ctinus** [comment]
Ok. I have a raspbian raspberry pi and I would be more than happy to help!

**Comment by 1ctinus** [comment]
should i close the issue?

**Comment by Henryws** [comment]
Wait are you saying you asked and no one helped and you want help making one?

**Comment by 1ctinus** [comment]
I didn't ask yet. sorry about that
