### ISSUE TITLE
Add a guide that explains how we can expand pacstall 

### ISSUE THREAD

**Issue by Vanderscycle** [Henryws/pacstall-programs#2]
**Is your feature request related to a problem? Please describe.**
Please add a .md file explaining how we can add new packages to pacstall

**Describe the solution you'd like**
Simple .md file with reading ressources on how to help expand

**Describe alternatives you've considered**
I read some of the .pacscript files, and I think I get the idea but a clear explanation would help.

**Additional context**
I use pacman and yay on manjaro, but I've never delved deeper into the aur library and your project might be a great way for alot of people to learn and expand debian system capabilities.

Thanks,

**Comment by Henryws** [comment]
Working on that now

**Comment by Henryws** [comment]
Done. Send a pull request if you want to add one
