### ISSUE TITLE
text-based package list, for wget/curl and awk/grep

### ISSUE THREAD

**Issue by erikLundstedt** [Henryws/pacstall-programs#4]
**Is your feature request related to a problem? Please describe.**
I'm working on a gui-ish(fzf based) terminal interface to (fuzzy)search and install packages(simlar to /version of the script called pkginst in [this](https://gitlab.com/scripts16/package-management-scripts) repo)
the way it works is that it querries the package list for the search "word" in $1 and lists the result to the user, allowing the user to fuzzyfind the chosen package(s)

this would however not work at the moment

**sulution 0**
**Describe the solution you'd like**
the easiest way would probably be to just run `ls|grep -v packageList>packagelist.txt` in the packages directory

**long-term, possible solution**
**Describe alternatives you've considered**

the optimal would be to make the search option work like the aptitude search option, IE search by parts of words and returning a grep or awk-friendly list, but that might take more time than needed

**Additional context**
how the one i made for the main repo, looks
![$ pkgInst vim](https://user-images.githubusercontent.com/36701667/117219369-6a836e80-ae05-11eb-8c06-2d3572fe5225.jpg)

**Comment by Henryws** [comment]
I've tried this before but I am terrible at bash-completion scripts so if you could try that I would gladly accept it.
But I think your talking about if I tried to run `sudo pacstall -I neof`, it would say something like `did you mean neofetch?`. Maybe. I just have terrible execution skills so if I saw someone do it, I could replicate but it's just hard for me to do it by myself

**Comment by erikLundstedt** [comment]
Try running 'aptitude search vim' assuming you have aptitude installed
Might need sudo
Should work with apt-get


I'm not talking about autocompletion

The way the search currently works is a bit more than a simple search while not "returning" easily pipeable data

Simply have it return a list of programs in the repo as if someone ran 'ls|grep $1'

**Comment by erikLundstedt** [comment]
> Try running 'aptitude search vim' assuming you have aptitude installed
> Might need sudo
> 
> I'm not talking about autocompletion
> 
> The way the search currently works is a bit more than a simple search while not "returning" easily pipeable data
> 
> Simply have it return a list of programs in the repo as if someone ran 'ls|grep $1'

\>sudo aptitude search neovim
```
i   neovim                                                      - heavily refactored vim fork                                          
p   neovim:i386                                                 - heavily refactored vim fork                                          
i   neovim-qt                                                   - neovim client library and GUI                                        
p   neovim-qt:i386                                              - neovim client library and GUI                                        
i A neovim-runtime                                              - heavily refactored vim fork (runtime files)                          
v   neovim-runtime:i386                                         -                                                                      
i A python-neovim                                               - Python2 library for scripting Neovim processes through its msgpack-rp
v   python2.7-neovim                                            -                                                                      
i A python3-neovim                                              - transitional dummy package                                           
p   ruby-neovim                                                 - Ruby client for Neovim                                          
```
the part I'm interested in is the package name(s)
and possibly the description

**Comment by Henryws** [comment]
And fuzzy search it for package names? I could do that

**Comment by erikLundstedt** [comment]
> And fuzzy search it for package names? I could do that

sounds good

make sure to read my edits, I think it makes it a bit clearer what im looking for/trying to describe
the fuzzy search part,i will also implement in the "front-end"as im using fzf for the menus but its also good if the package-manager itself has something like it

mainly try to make it work like the aptitude implementation as that is the one that i found is most grep/awk friendly
the goal of this is to make the search feature more unix-pipe friendly as it now seems to do the same(or something very similar) as the --install flag

## current behaviour
pacstall --search vi
`[!] ERROR: vi doesn't seem to exist`
pacstall --search vim
`vim is available. Do you want to view the pacscript [Y/n] n`

## preferred behaviour(awk-friendly)
pacstall --search vi
`vim                - vi-improved, a greatly improved version of the good old UNIX editor Vi`
pacstall --search vim
`vim                - vi-improved, a greatly improved version of the good old UNIX editor Vi`

**Comment by Henryws** [comment]
Does fzf have a way to just output it to stdin instead of piping into a menu?

**Comment by Henryws** [comment]
The main problem is I want it to be automated. I don't want to add a line of text to a file every time a package gets added. I want it to do that automatically

**Comment by erikLundstedt** [comment]
> Does fzf have a way to just output it to stdin instead of piping into a menu?

fzf works like dmenu or rofi --dmenu but works without x11 and allows for previews(and a lot more)
it takes a \\n separated list of items and puts them in a fuzzy-searchable list/menu, pressing enter(configurable) makes it output the selected item(s) to stdout

are you using it yourself? I was thinking of making a script myself to use as a terminal "front end" to pacstall similar to the search feature of most graphical package-managers

**Comment by Henryws** [comment]
I'm not making a front-end. You can do that. But I want to help you and that would mean I would need a manifest or something that lists all the available packages. The hard part is making the list. If pacstall gets to big, I don't want to edit a super large file manually

**Comment by erikLundstedt** [comment]
> I'm not making a front-end. You can do that. But I want to help you and that would mean I would need a manifest or something that lists all the available packages. The hard part is making the list. If pacstall gets to big, I don't want to edit a super large file manually

the snippet i made `ls|grep -v packageList>packagelist.txt` automaticaly overrides the packagelist.txt file
it might become somewhat heavy but it should work for a while


im not really used to how wget/curl/git works but it might allow for some kind of directory listing

**Comment by Henryws** [comment]
You can replace every space with a newline with `tr ' ' '\n' when you curl the file
