### ISSUE TITLE
Error: breaks while testing new pacscript

### ISSUE THREAD

**Issue by SomethingGeneric** [Henryws/pacstall-programs#5]
**Describe the bug**
The only error I get from pacstall about my pacscript file is `Error: breaks`

Source is my fork [here](https://github.com/SomethingGeneric/pacstall-programs/blob/master/packages/nofetch/nofetch.pacscript)

**To Reproduce**
1. `cd packages/nofetch`
2. `sudo pacstall -Il nofetch`

**Expected behavior**
Seems like I have (what should be) a working pacscript, but it doesn't, and I'm not getting any pointers as to why.

**Screenshots**
![Screenshot from 2021-05-05 21-28-04](https://user-images.githubusercontent.com/12242178/117229357-ddcab780-ade8-11eb-99ae-b10ea92fed45.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 21.04

**Comment by SomethingGeneric** [comment]
I figure this is probably user error but whatever I'm doing wrong could probably be a tip in the `make-a-pacscript` file :)

**Comment by SomethingGeneric** [comment]
Wait ok so the **one time** I screenshot it gives me a syntax error. So the problem is two-fold. One, why does my function that fits bash syntax cause an error, and if I'm just braindead, then why does the error only show up _sometimes_

**Comment by Henryws** [comment]
You should add a prepare and build function with the command `true` inside. Next is to make the breaks variable some random thing like `akjfdlakfhk`. I'm working on leaving out the breaks variable but thats how it is now. Also for prepare now that I think about it, it should have this inside:
```bash
prepare() {
   sudo mkdir -p /usr/src/pacstall/nofetch/bin
   mv nofetch /usr/src/pacstall/nofetch/bin
}

**Comment by SomethingGeneric** [comment]
Ok, new progress. `breaks` was the name of the attribute which I didn't specify. Setting something like `breaks="foo"` solves that issue, but now I've got more fork to do

**Comment by SomethingGeneric** [comment]
> You should add a prepare and build function with the command `true` inside. Next is to make the breaks variable some random thing like `akjfdlakfhk`. I'm working on leaving out the breaks variable but thats how it is now. Also for prepare now that I think about it, it should have this inside:
> 
> ```shell
> prepare() {
>    sudo mkdir -p /usr/src/pacstall/nofetch/bin
>    mv nofetch /usr/src/pacstall/nofetch/bin
> }
> ```

Ah, the prepare function is always required? Ok.

**Comment by Henryws** [comment]
`/usr/src/pacstall/foo` is the pseudo directory. Stow will symlink the files inside to `/`. So if I run `tree /usr/src/pacstall/neofetch`, this is what it outputs:
```bash
/usr/src/pacstall/neofetch
└── usr
    ├── bin
    │   └── neofetch
    └── share
        └── man
            └── man1
                └── neofetch.1
```
But stow will symlink that stuff to `/` if that helps.

**Comment by SomethingGeneric** [comment]
So, here's my new issue and pacscript.
```sh
name="nofetch"
version="1.0"
url="https://github.com/jnats/nofetch/archive/refs/tags/v1.0.zip"
description="The simple man's fetch tool"
breaks="foo"
hash="92e1d4b047b2f5c5ba99d2afa922a65004321cd7930027183ee8c57d393cbb78"

build() {
    true
}

prepare() {
    sudo mkdir -p /usr/src/pacstall/nofetch/bin
    chmod +x nofetch
    mv nofetch /usr/src/pacstall/nofetch/bin
}
```


And the output
![Screenshot from 2021-05-05 21-36-00](https://user-images.githubusercontent.com/12242178/117229888-e96aae00-ade9-11eb-93ed-5c5065f12704.png)

**Comment by Henryws** [comment]
It works for me:
```bash
➜  ~ vim nofetch.pacscript
➜  ~ sudo pacstall -Il nofetch
[sudo] password for henry:
Do you want to view the pacscript first [Y/n] n
[+] INFO: Sourcing pacscript
[+] INFO: Running checks
[+] INFO: URL exists
[+] INFO: Installing dependencies
[+] INFO: Retrieving packages
v1.0.zip          100%[==========>]  18.70K  --.-KB/s    in 0.05s
[+] INFO: Installing
install: missing file operand
Try 'install --help' for more information.
[+] INFO: Symlinking files
➜  ~ nofetch

 > i would be lead to believe that / is mounted
 > Linux Mint Linux 5.4.0-60-generic x86_64

➜  ~
```
Perhaps you should change all of the `/usr/src/pacstall/nofetch/bin` to  `/usr/src/pacstall/nofetch/usr/bin`

**Comment by Henryws** [comment]
Although proper pacscripts would look like this:
```bash
name="nofetch"
version="1.0"
url="https://github.com/jnats/nofetch/archive/refs/tags/v1.0.zip"
description="The simple man's fetch tool"
breaks="foo"
hash="92e1d4b047b2f5c5ba99d2afa922a65004321cd7930027183ee8c57d393cbb78"

prepare() {
    true
}

build() {
    true
}

install() {
    sudo mkdir -p /usr/src/pacstall/nofetch/usr/bin
    chmod +x nofetch
    mv nofetch /usr/src/pacstall/nofetch/usr/bin
}
```

**Comment by SomethingGeneric** [comment]
So, I replaced the path as you suggested to match `/usr/bin`. Unfortunately, still getting the same error from `stow`.

![Screenshot from 2021-05-05 21-40-36](https://user-images.githubusercontent.com/12242178/117230237-a0672980-adea-11eb-8956-370bb05bf7e4.png)

**Comment by Henryws** [comment]
Oh, that means that you already installed nofetch to the system and pacstall won't overwrite files

**Comment by SomethingGeneric** [comment]
Ope, yep. A good ol `rm -rfv /usr/src/pacstall/nofetch`. Thanks!
