### ISSUE TITLE
Make packagelist newline separeated instead of space separated

### ISSUE THREAD

**Issue by kaistian** [Henryws/pacstall-programs#61]
**Is your feature request related to a problem? Please describe.**
Since packagelist is space separated it is somewhat harder to add a package to it in alphabetic order.
It also make merging harder since every PR with the same parent would conflict on packagelist after the first one is merged.

**Describe the solution you'd like**
Every package name is on it own line.

**Describe alternatives you've considered**
None.

**Additional context**
This would make it easy to add a package in vim. Just add the line somewhere and run `:sort` and it would be sorted alphabetically.
If the name is own line, there will be less conflicts since it more likely the changes are some lines apart and git have no problem merging the changes.

**Comment by Henryws** [comment]
Well I just run `git pull` every day and cd into the packages directory and do a `for i in $(ls) ; do echo $i > ../packaglist` (not exactly, but I think you get it). Besides, everyone would have to update or they wouldn’t be able to do a search (I think)

**Comment by kaistian** [comment]
I actually use `ls | paste -sd ' ' >../packagelist`, if the packages had it own line it would be `ls >../packagelist`.
But if packages was on it own line I could easily just add the new package name with vim in the file directly without using a command before I made a push and a PR. And for those using command `ls >../packagelist` is also very easy.

It would also make your life easier, since less PR would have merge conflict.

> Besides, everyone would have to update or they wouldn’t be able to do a search (I think)

Yes, everybody that create a PR should/must update this file for the search to work, so this change is only about the separator in packagelist.
The packagelist is only used in `misc/scripts/search.sh`
`SELECTED=$(curl -s "$REPO"/packagelist | tr ' ' '\n' | fzf -q "$SEARCH" --preview="curl -s "$REPO"/packages/{}/{}.pacscript")`

This will work without any change if packagelist is separated with newline instead of space. But the `tr ' ' '\n'` could be removed since the file file is already separated with newlines.

Hopefully this made it more clear what the proposal is about.

**Comment by erikLundstedt** [comment]
> Well I just run `git pull` every day and cd into the packages directory and do a `for i in $(ls) ; do echo $i > ../packaglist` (not exactly, but I think you get it). Besides, everyone would have to update or they wouldn’t be able to do a search (I think)

i`m with O(I)P
having the list be newline separated would make booth your own search-script easier (less code=easier to understand),and it would do the same to pacget,my own script
and for everyone else too




us booth already have to run the list thru tr " " "\n" in order for the search to work
